# Generated by Django 4.0 on 2021-12-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, unique=True)),
                ('cat_desc', models.TextField(blank=True, max_length=100)),
                ('cat_slug', models.SlugField(max_length=100)),
                ('cat_image', models.ImageField(upload_to='uploads/categories')),
            ],
        ),
    ]
